config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, skip: [:registrations], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers, controllers: {
    registrations: "customer/registrations",
    sessions: 'customer/sessions'
  }


  namespace :admin do
    resources :customers, only:[:show, :index, :edit, :update]
    resources :posts, only:[:show, :index, :edit, :update, :destroy]
  end

  root to: "customer/homes#top"
  get '/about' => 'customer/homes#about'

  scope module: :customer do
    get 'customers/:id/favorites' => 'customers#favorites', as: 'favorites'
    get 'customers/:id/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    patch 'customers/:id/withdraw' => 'customers#withdraw', as: 'withdraw'
    get 'customers/:id/prefecture' => 'customers#prefecture_index', as: 'prefecture'
    resources :customers, only:[:show, :index, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get 'follow' => 'relationships#follow', as:'follow'
    end
    resources :posts, except:[:new] do
      resources :post_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
  end

  get "search" => "searches#search"

  devise_scope :customer do
    post 'customer/guest_sign_in', to: 'customer/sessions#guest_sign_in'
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def search
		@model = params[:model]
		@content = params[:content]
		if @model == 'customer'
		  @records = Customer.search_for(@content).page(params[:page])
		elsif @model == 'post'
		  @records = Post.search_for(@content).page(params[:page]).order(created_at: :desc)
		elsif @model == 'prefecture'
		  if Prefecture.exists?(name: @content)
		    @prefecture = Prefecture.find_by(name: @content)
		    @records = @prefecture.customers.page(params[:page])
		  else
		    @records = Customer.page(params[:page])
		  end
		end
  end

end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_form.html.erb
<%= form_with url: search_path, local: true, method: :get, class: "search-container d-flex justify-content-end" do |f| %>
  <%= f.select :model, options_for_select({ "user" => "customer", "post" => "post", "prefecture" => "prefecture" }) %>
  <div class="search-box">
    <%= f.text_field :content, placeholder: "search", style: "border: none" %>
    <%= f.button :type => "submit", style: "border: none" do %>
      <i class="fas fa-search"></i>
    <% end %>
  </div>
<% end %>

app/views/searches/search.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-12 mt-3'>
      <% if admin_signed_in? %>
        <% if @model == 'customer' %>
        	<h3 class="text-center mt-5">users search for "<%= @content %>"</h3>
        	<% if @records.exists? %>
            <%= render 'admin/customers/index', customers: @records %>
          <% else %>
            <p class="text-center">検索結果がありませんでした</p>
          <% end %>
        <% elsif @model == 'post' %>
        	<h3 class="text-center mt-5">posts search for "<%= @content %>"</h3>
        	<% if @records.exists? %>
          	<%= render 'admin/posts/index', posts: @records %>
          <% else %>
            <p class="text-center">検索結果がありませんでした</p>
          <% end %>
        <% elsif @model == 'prefecture' %>
        	<h3 class="text-center mt-5">prefectures search for "<%= @content %>"</h3>
        	<% if @records.exists? %>
            <%= render 'admin/customers/index', customers: @records %>
          <% else %>
            <p class="text-center">検索結果がありませんでした</p>
          <% end %>
        <% end %>
      <% else %>
        <% if @model == 'customer' %>
        	<h3 class="text-center mt-5">users search for "<%= @content %>"</h3>
          <% if @records.exists? %>
            <%= render 'customer/customers/index', customers: @records %>
          <% else %>
            <p class="text-center">検索結果がありませんでした</p>
          <% end %>
        <% elsif @model == 'post' %>
        	<h3 class="text-center mt-5">posts search for "<%= @content %>"</h3>
        	<% if @records.exists? %>
          	<%= render 'customer/posts/index', posts: @records %>
          <% else %>
            <p class="text-center">検索結果がありませんでした</p>
          <% end %>
        <% elsif @model == 'prefecture' %>
        	<h3 class="text-center mt-5">prefectures search for "<%= @content %>"</h3>
        	<% if @records.exists? %>
            <%= render 'customer/customers/index', customers: @records %>
          <% else %>
            <p class="text-center">検索結果がありませんでした</p>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>